site_name: CI/CD Examples
site_description: Examples on how to develop CI/CD pipelines and how to configure development environment for working with CI/CD pipelines.
site_url: https://kangasta.github.io/cicd-examples/
repo_name: kangasta/cicd-examples
repo_url: https://github.com/kangasta/cicd-examples
copyright: CI/CD Examples is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0<img style="height:18px!important;margin-left:9px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt=""><img style="height:18px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt=""><img style="height:18px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg" alt=""></a>

extra_css:
  - assets/extra.css

docs_dir: docs/
edit_uri: edit/main/docs/

nav:
  - Home: README.md
  - Docker:
      - ./examples/docker/docker-on-wsl/README.md
  - Jenkins:
      - ./examples/jenkins/jenkins-host-docker/README.md
      - ./examples/jenkins/ansible-kubernetes/README.md
      - ./examples/jenkins/build-status-pipelines/README.md
      - ./examples/jenkins/parallel-robot-pipeline/README.md
      - ./examples/jenkins/sonarqube-jenkins/README.md
not_in_nav: |
  assets/README.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.svg
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Source Sans 3
    code: Source Code Pro
  language: en
  features:
    - content.action.edit
    - content.action.view
    - navigation.instant
    - navigation.sections

plugins:
  - git-committers:
      repository: kangasta/cicd-examples
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  - social

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
