apiVersion: v1
kind: Namespace
metadata:
  name: pull-through-cache
  labels:
    name: pull-through-cache
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: pull-through-cache
data:
  config.yml: |
    version: 0.1
    http:
      addr: 0.0.0.0:80
    proxy:
      remoteurl: https://registry-1.docker.io
    storage:
      filesystem: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: pull-through-cache
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        volumeMounts:
        - name: registry-config
          mountPath: "/etc/docker/registry/"
          readOnly: true
      volumes:
      - name: registry-config
        configMap:
          name: registry-config
          items:
          - key: "config.yml"
            path: "config.yml"
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: pull-through-cache
  labels:
    app: registry
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: registry
